#compose 文件的版本
version: "3"
# 一个services 下面包含多个项目服务
services:
  # 服务1
  docker-demo:
    #镜像地址
    image: registry.cn-hangzhou.aliyuncs.com/duchong/demo-repo/summer_travel/docker-demo:1.0
    #容器名称
    container_name: docker-demo
    #无论如何容器都会重启
    restart: always
    #映射端口
    ports:
      - "8080:8080"
  # 服务2
  docker-demo2:
    #镜像地址
    image: registry.cn-hangzhou.aliyuncs.com/duchong/demo-repo/summer_travel/docker-demo2:1.0
    #容器名称
    container_name: docker-demo2
    #无论如何容器都会重启
    restart: always
    #映射端口
    ports:
      - "8081:8081"

  # 服务3、4、5